### ISSUE TITLE
Add configuration button

### ISSUE THREAD

**Issue by ftonato** [ftonato/pomodoro-app#11]
Add options to configure layout colors and set time to **short time** and **long time** options.

**Comment by GBeckerRS** [comment]
Sound beep on timeout

**Comment by ftonato** [comment]
@GBeckerRS I will check this! Thank you.

**Comment by ftonato** [comment]
@GBeckerRS Do you suggest the customization of your notification sound or just receive the [notificiation with sound](https://github.com/ftonato/pomodoro-app/issues/6)?

**Comment by ftonato** [comment]
Are you comfortable working on it?

/cc @RhnSharma, @eugeniumegherea and/or @r33beers

**Comment by ftonato** [comment]
I'm closing outdated issues and pull-requests that are no longer relevant given how much time has passed since they were opened.
