### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by ftonato** [ftonato/pomodoro-app#16]
Today we use this dependencies:

```
"devDependencies": {
    "electron-prebuilt": "^0.37.4",
    "google-closure-compiler-js": "^20160828.0.1",
    "gulp": "^3.9.1",
    "gulp-clean": "^0.3.2",
    "gulp-minify-css": "^1.2.4",
    "gulp-rename": "^1.2.2",
    "jshint": "^2.9.3",
    "vinyl": "^1.2.0" // 2.2.0
  },
  "dependencies": {
    "node-notifier": "^4.6.1" // 5.2.1
}
```

We can update almost all of them
We can update almost all of them, but it's important to keep our project "safe" (tip: [npm audit](https://docs.npmjs.com/cli/audit)) :)

I suggest to update for this versions:

`gulp-clean: 0.4.0`
`gulp-minify-css: ? // This package has been deprecated`
`gulp-rename: 1.4.0`
`jshint: 2.9.6`
`vinyl: 2.2.0`

> For other dependencies can use [`NCU`](https://github.com/tjunnone/npm-check-updates) package to verify this.

**Comment by RhnSharma** [comment]
I am working on this!

**Comment by ftonato** [comment]
It's yours, good luck o/

**Comment by rjbeers** [comment]
@RhnSharma I have a pull request open that updates everything, except @ftonato is interested in getting gulp to v4.0.0. That requires significant rework to the gulp.js file. Want to take that on?

**Comment by RhnSharma** [comment]
@r33beers No
