### ISSUE TITLE
Add shortcuts on README

### ISSUE THREAD

**Issue by ftonato** [ftonato/pomodoro-app#22]
Today, we can use this shortcuts:

`Ctrl + S`: **Start**
`Ctrl + R`: **Stop**
`Ctrl + 1`: **To set pomodoro time: 05:00**
`Ctrl + 2`: **To set pomodoro time: 10:00**
`Ctrl + 3`: **To set pomodoro time: 25:00**

> If the timer is running or in breaktime, you cannot change the pomodoro time.

It's important to add options on [README.md](https://github.com/ftonato/pomodoro-app/blob/master/README.md) and [README.pt-br.md](https://github.com/ftonato/pomodoro-app/blob/master/README.pt-br.md).

It's not necessary add translate to pt-BR on _README.pt-br_. I will do this at the same _PR_ :)

**Comment by eugeniumegherea** [comment]
I'm doing it! PR incoming
